// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.proto

package quick_find_services_im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMessageRequest struct {
	From                 int32    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{0}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SendMessageRequest) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TranslateRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateRequest) Reset()         { *m = TranslateRequest{} }
func (m *TranslateRequest) String() string { return proto.CompactTextString(m) }
func (*TranslateRequest) ProtoMessage()    {}
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{1}
}

func (m *TranslateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateRequest.Unmarshal(m, b)
}
func (m *TranslateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateRequest.Marshal(b, m, deterministic)
}
func (m *TranslateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateRequest.Merge(m, src)
}
func (m *TranslateRequest) XXX_Size() int {
	return xxx_messageInfo_TranslateRequest.Size(m)
}
func (m *TranslateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateRequest proto.InternalMessageInfo

func (m *TranslateRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type TranslateResponse struct {
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateResponse) Reset()         { *m = TranslateResponse{} }
func (m *TranslateResponse) String() string { return proto.CompactTextString(m) }
func (*TranslateResponse) ProtoMessage()    {}
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{2}
}

func (m *TranslateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateResponse.Unmarshal(m, b)
}
func (m *TranslateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateResponse.Marshal(b, m, deterministic)
}
func (m *TranslateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateResponse.Merge(m, src)
}
func (m *TranslateResponse) XXX_Size() int {
	return xxx_messageInfo_TranslateResponse.Size(m)
}
func (m *TranslateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateResponse proto.InternalMessageInfo

func (m *TranslateResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendMessageResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{3}
}

func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func (m *SendMessageResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*SendMessageRequest)(nil), "quick.find.services.im.SendMessageRequest")
	proto.RegisterType((*TranslateRequest)(nil), "quick.find.services.im.TranslateRequest")
	proto.RegisterType((*TranslateResponse)(nil), "quick.find.services.im.TranslateResponse")
	proto.RegisterType((*SendMessageResponse)(nil), "quick.find.services.im.SendMessageResponse")
}

func init() { proto.RegisterFile("im.proto", fileDescriptor_36f2114a3e4ddb9e) }

var fileDescriptor_36f2114a3e4ddb9e = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4e, 0xc3, 0x30,
	0x0c, 0xc6, 0xd5, 0x02, 0x63, 0x35, 0x12, 0x02, 0x23, 0x4d, 0xd5, 0x4e, 0x53, 0x0f, 0x50, 0x40,
	0xe4, 0x00, 0x4f, 0xc1, 0x61, 0x97, 0x8c, 0x07, 0xa0, 0x6c, 0x2e, 0x8a, 0x58, 0x92, 0x2d, 0x4e,
	0x11, 0x4f, 0xca, 0xf3, 0x20, 0xa5, 0x61, 0x0a, 0x7f, 0x26, 0xf5, 0x66, 0x47, 0xbf, 0xef, 0x8b,
	0xfd, 0x19, 0xc6, 0x4a, 0x8b, 0x8d, 0xb3, 0xde, 0xe2, 0x64, 0xdb, 0xa9, 0xe5, 0x9b, 0x68, 0x95,
	0x59, 0x09, 0x26, 0xf7, 0xae, 0x96, 0xc4, 0x42, 0xe9, 0x4a, 0x02, 0x2e, 0xc8, 0xac, 0xe6, 0xc4,
	0xdc, 0xbc, 0x92, 0xa4, 0x6d, 0x47, 0xec, 0x11, 0xe1, 0xb0, 0x75, 0x56, 0x97, 0xd9, 0x2c, 0xab,
	0x8f, 0x64, 0xa8, 0xf1, 0x14, 0x72, 0x6f, 0xcb, 0x3c, 0xbc, 0xe4, 0xde, 0x62, 0x09, 0xc7, 0xba,
	0x57, 0x95, 0x07, 0xb3, 0xac, 0x2e, 0xe4, 0x77, 0x5b, 0x5d, 0xc2, 0xd9, 0x93, 0x6b, 0x0c, 0xaf,
	0x1b, 0x9f, 0x3a, 0x7a, 0xfa, 0xf0, 0xc1, 0xb1, 0x90, 0xa1, 0xae, 0xae, 0xe0, 0x3c, 0xe1, 0x78,
	0x63, 0x0d, 0xd3, 0x0e, 0xcc, 0x13, 0xf0, 0x0e, 0x2e, 0x7e, 0x0c, 0x19, 0xd1, 0x09, 0x8c, 0x1c,
	0x71, 0xb7, 0xee, 0x5d, 0xc7, 0x32, 0x76, 0xf7, 0x9f, 0x19, 0xc0, 0xe3, 0x7c, 0x11, 0xb7, 0xc4,
	0x16, 0x4e, 0x12, 0x35, 0xde, 0x88, 0xff, 0xa3, 0x10, 0x7f, 0x73, 0x98, 0xde, 0x0e, 0x62, 0xe3,
	0x38, 0xcf, 0x50, 0xec, 0xd6, 0xc1, 0x7a, 0x9f, 0xf2, 0x77, 0x32, 0xd3, 0xeb, 0x01, 0x64, 0xff,
	0xc3, 0xcb, 0x28, 0xdc, 0xf2, 0xe1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x29, 0xd0, 0xac, 0xe4, 0xd7,
	0x01, 0x00, 0x00,
}
