// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friend.proto

package quick_find_services_friend

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddFriendRequest struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FriendId             int32    `protobuf:"varint,2,opt,name=friendId,proto3" json:"friendId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendRequest) Reset()         { *m = AddFriendRequest{} }
func (m *AddFriendRequest) String() string { return proto.CompactTextString(m) }
func (*AddFriendRequest) ProtoMessage()    {}
func (*AddFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{0}
}

func (m *AddFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendRequest.Unmarshal(m, b)
}
func (m *AddFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendRequest.Marshal(b, m, deterministic)
}
func (m *AddFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendRequest.Merge(m, src)
}
func (m *AddFriendRequest) XXX_Size() int {
	return xxx_messageInfo_AddFriendRequest.Size(m)
}
func (m *AddFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendRequest proto.InternalMessageInfo

func (m *AddFriendRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AddFriendRequest) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

type FriendResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendResponse) Reset()         { *m = FriendResponse{} }
func (m *FriendResponse) String() string { return proto.CompactTextString(m) }
func (*FriendResponse) ProtoMessage()    {}
func (*FriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{1}
}

func (m *FriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendResponse.Unmarshal(m, b)
}
func (m *FriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendResponse.Marshal(b, m, deterministic)
}
func (m *FriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendResponse.Merge(m, src)
}
func (m *FriendResponse) XXX_Size() int {
	return xxx_messageInfo_FriendResponse.Size(m)
}
func (m *FriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FriendResponse proto.InternalMessageInfo

func (m *FriendResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type FriendJoinUser struct {
	Friend               int32    `protobuf:"varint,1,opt,name=friend,proto3" json:"friend,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendJoinUser) Reset()         { *m = FriendJoinUser{} }
func (m *FriendJoinUser) String() string { return proto.CompactTextString(m) }
func (*FriendJoinUser) ProtoMessage()    {}
func (*FriendJoinUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{2}
}

func (m *FriendJoinUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendJoinUser.Unmarshal(m, b)
}
func (m *FriendJoinUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendJoinUser.Marshal(b, m, deterministic)
}
func (m *FriendJoinUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendJoinUser.Merge(m, src)
}
func (m *FriendJoinUser) XXX_Size() int {
	return xxx_messageInfo_FriendJoinUser.Size(m)
}
func (m *FriendJoinUser) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendJoinUser.DiscardUnknown(m)
}

var xxx_messageInfo_FriendJoinUser proto.InternalMessageInfo

func (m *FriendJoinUser) GetFriend() int32 {
	if m != nil {
		return m.Friend
	}
	return 0
}

func (m *FriendJoinUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListRequest struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type ListResponse struct {
	Uid                  int32             `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	List                 []*FriendJoinUser `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ListResponse) GetList() []*FriendJoinUser {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*AddFriendRequest)(nil), "quick.find.services.friend.AddFriendRequest")
	proto.RegisterType((*FriendResponse)(nil), "quick.find.services.friend.FriendResponse")
	proto.RegisterType((*FriendJoinUser)(nil), "quick.find.services.friend.FriendJoinUser")
	proto.RegisterType((*ListRequest)(nil), "quick.find.services.friend.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "quick.find.services.friend.ListResponse")
}

func init() { proto.RegisterFile("friend.proto", fileDescriptor_2b65cbc293af6bbd) }

var fileDescriptor_2b65cbc293af6bbd = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x1b, 0x4b, 0x3b, 0x2d, 0x52, 0xe6, 0x20, 0x21, 0x17, 0x4b, 0x2e, 0x06, 0x91,
	0x3d, 0xd4, 0xab, 0x88, 0x5e, 0x04, 0xc5, 0xd3, 0x8a, 0x07, 0x6f, 0x6a, 0x77, 0x0a, 0x8b, 0x75,
	0xd3, 0xee, 0x6c, 0xfc, 0xa0, 0x7e, 0x22, 0xc9, 0xee, 0x26, 0xf8, 0x87, 0xd6, 0xde, 0xf6, 0x85,
	0xdf, 0xbc, 0x99, 0xf7, 0x08, 0x4c, 0x96, 0x56, 0x93, 0x51, 0x62, 0x6d, 0x2b, 0x57, 0x61, 0xbe,
	0xa9, 0xf5, 0xe2, 0x4d, 0x2c, 0xb5, 0x51, 0x82, 0xc9, 0x7e, 0xe8, 0x05, 0xb1, 0x08, 0x44, 0x71,
	0x05, 0xd3, 0x6b, 0xa5, 0x6e, 0xbc, 0x90, 0xb4, 0xa9, 0x89, 0x1d, 0x4e, 0xa1, 0x5f, 0x6b, 0x95,
	0x25, 0xb3, 0xa4, 0x3c, 0x90, 0xcd, 0x13, 0x73, 0x18, 0x06, 0xfe, 0x56, 0x65, 0x3d, 0xff, 0xb9,
	0xd3, 0x45, 0x09, 0x87, 0xed, 0x38, 0xaf, 0x2b, 0xc3, 0x84, 0x47, 0x30, 0xb0, 0xc4, 0xf5, 0xca,
	0x79, 0x8b, 0xa1, 0x8c, 0xaa, 0xb8, 0x68, 0xc9, 0xbb, 0x4a, 0x9b, 0x47, 0x26, 0xdb, 0x90, 0xc1,
	0x27, 0x2e, 0x8b, 0x0a, 0x11, 0x52, 0xf3, 0xf2, 0x4e, 0x7e, 0xd7, 0x48, 0xfa, 0x77, 0x71, 0x0c,
	0xe3, 0x7b, 0xcd, 0x6e, 0xeb, 0x91, 0xc5, 0x33, 0x4c, 0x02, 0x10, 0xcf, 0xf8, 0x1b, 0xe3, 0x12,
	0xd2, 0x95, 0x66, 0x97, 0xf5, 0x66, 0xfd, 0x72, 0x3c, 0x3f, 0x15, 0xdb, 0x7b, 0x11, 0x3f, 0x0f,
	0x95, 0x7e, 0x6e, 0xfe, 0x99, 0xb4, 0x09, 0x1e, 0x22, 0x8e, 0x04, 0xa3, 0xae, 0x3f, 0x3c, 0xdb,
	0xe5, 0xf8, 0xbb, 0xe6, 0x7c, 0x8f, 0xfd, 0x5d, 0x96, 0x27, 0x48, 0x9b, 0x6c, 0x78, 0xb2, 0x6b,
	0xe6, 0x5b, 0x3d, 0x79, 0xf9, 0x3f, 0x18, 0xac, 0x5f, 0x07, 0xfe, 0x27, 0x39, 0xff, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x2b, 0x45, 0x63, 0xf9, 0x34, 0x02, 0x00, 0x00,
}
