// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: friend.proto

package quick_find_services_friend

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FriendServices service

type FriendServicesService interface {
	AddFriend(ctx context.Context, in *AddFriendRequest, opts ...client.CallOption) (*FriendResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type friendServicesService struct {
	c    client.Client
	name string
}

func NewFriendServicesService(name string, c client.Client) FriendServicesService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "quick.find.services.friend"
	}
	return &friendServicesService{
		c:    c,
		name: name,
	}
}

func (c *friendServicesService) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...client.CallOption) (*FriendResponse, error) {
	req := c.c.NewRequest(c.name, "FriendServices.AddFriend", in)
	out := new(FriendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServicesService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "FriendServices.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FriendServices service

type FriendServicesHandler interface {
	AddFriend(context.Context, *AddFriendRequest, *FriendResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterFriendServicesHandler(s server.Server, hdlr FriendServicesHandler, opts ...server.HandlerOption) error {
	type friendServices interface {
		AddFriend(ctx context.Context, in *AddFriendRequest, out *FriendResponse) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
	}
	type FriendServices struct {
		friendServices
	}
	h := &friendServicesHandler{hdlr}
	return s.Handle(s.NewHandler(&FriendServices{h}, opts...))
}

type friendServicesHandler struct {
	FriendServicesHandler
}

func (h *friendServicesHandler) AddFriend(ctx context.Context, in *AddFriendRequest, out *FriendResponse) error {
	return h.FriendServicesHandler.AddFriend(ctx, in, out)
}

func (h *friendServicesHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.FriendServicesHandler.List(ctx, in, out)
}
