// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topic.proto

package quick_find_services_topic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Publish struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Publish) Reset()         { *m = Publish{} }
func (m *Publish) String() string { return proto.CompactTextString(m) }
func (*Publish) ProtoMessage()    {}
func (*Publish) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{0}
}

func (m *Publish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Publish.Unmarshal(m, b)
}
func (m *Publish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Publish.Marshal(b, m, deterministic)
}
func (m *Publish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Publish.Merge(m, src)
}
func (m *Publish) XXX_Size() int {
	return xxx_messageInfo_Publish.Size(m)
}
func (m *Publish) XXX_DiscardUnknown() {
	xxx_messageInfo_Publish.DiscardUnknown(m)
}

var xxx_messageInfo_Publish proto.InternalMessageInfo

func (m *Publish) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Publish) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Publish) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Comment struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{1}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Topic struct {
	Title                string     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Uid                  int32      `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content              string     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Like                 int32      `protobuf:"varint,4,opt,name=like,proto3" json:"like,omitempty"`
	Comment              []*Comment `protobuf:"bytes,5,rep,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{3}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Topic) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Topic) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Topic) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *Topic) GetComment() []*Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type TopinJoinName struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Like                 int32    `protobuf:"varint,4,opt,name=like,proto3" json:"like,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopinJoinName) Reset()         { *m = TopinJoinName{} }
func (m *TopinJoinName) String() string { return proto.CompactTextString(m) }
func (*TopinJoinName) ProtoMessage()    {}
func (*TopinJoinName) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{4}
}

func (m *TopinJoinName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopinJoinName.Unmarshal(m, b)
}
func (m *TopinJoinName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopinJoinName.Marshal(b, m, deterministic)
}
func (m *TopinJoinName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopinJoinName.Merge(m, src)
}
func (m *TopinJoinName) XXX_Size() int {
	return xxx_messageInfo_TopinJoinName.Size(m)
}
func (m *TopinJoinName) XXX_DiscardUnknown() {
	xxx_messageInfo_TopinJoinName.DiscardUnknown(m)
}

var xxx_messageInfo_TopinJoinName proto.InternalMessageInfo

func (m *TopinJoinName) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TopinJoinName) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *TopinJoinName) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TopinJoinName) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *TopinJoinName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TopicList struct {
	List                 []*TopinJoinName `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TopicList) Reset()         { *m = TopicList{} }
func (m *TopicList) String() string { return proto.CompactTextString(m) }
func (*TopicList) ProtoMessage()    {}
func (*TopicList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{5}
}

func (m *TopicList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicList.Unmarshal(m, b)
}
func (m *TopicList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicList.Marshal(b, m, deterministic)
}
func (m *TopicList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicList.Merge(m, src)
}
func (m *TopicList) XXX_Size() int {
	return xxx_messageInfo_TopicList.Size(m)
}
func (m *TopicList) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicList.DiscardUnknown(m)
}

var xxx_messageInfo_TopicList proto.InternalMessageInfo

func (m *TopicList) GetList() []*TopinJoinName {
	if m != nil {
		return m.List
	}
	return nil
}

type PushResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResponse) Reset()         { *m = PushResponse{} }
func (m *PushResponse) String() string { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()    {}
func (*PushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{6}
}

func (m *PushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResponse.Unmarshal(m, b)
}
func (m *PushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResponse.Marshal(b, m, deterministic)
}
func (m *PushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResponse.Merge(m, src)
}
func (m *PushResponse) XXX_Size() int {
	return xxx_messageInfo_PushResponse.Size(m)
}
func (m *PushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushResponse proto.InternalMessageInfo

func (m *PushResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*Publish)(nil), "quick.find.services.topic.Publish")
	proto.RegisterType((*Comment)(nil), "quick.find.services.topic.Comment")
	proto.RegisterType((*ListRequest)(nil), "quick.find.services.topic.ListRequest")
	proto.RegisterType((*Topic)(nil), "quick.find.services.topic.Topic")
	proto.RegisterType((*TopinJoinName)(nil), "quick.find.services.topic.TopinJoinName")
	proto.RegisterType((*TopicList)(nil), "quick.find.services.topic.TopicList")
	proto.RegisterType((*PushResponse)(nil), "quick.find.services.topic.PushResponse")
}

func init() { proto.RegisterFile("topic.proto", fileDescriptor_7312ad0e4fa171e8) }

var fileDescriptor_7312ad0e4fa171e8 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x4a, 0x33, 0x31,
	0x14, 0x65, 0xda, 0x49, 0x7f, 0x6e, 0xbf, 0x0f, 0x24, 0x88, 0x8c, 0x5d, 0x95, 0x20, 0x75, 0x56,
	0xb3, 0xa8, 0x0b, 0x37, 0x05, 0x17, 0xae, 0xfc, 0x41, 0x4a, 0xda, 0x17, 0x68, 0xa7, 0xd1, 0x86,
	0x4e, 0x93, 0xe9, 0x24, 0x11, 0x7c, 0x16, 0xdf, 0xc4, 0xa7, 0x93, 0xdc, 0x99, 0x91, 0x76, 0xe1,
	0xb8, 0x10, 0x77, 0xf7, 0xc0, 0x39, 0xe7, 0xde, 0x73, 0x48, 0x60, 0x60, 0x75, 0x2e, 0xd3, 0x24,
	0x2f, 0xb4, 0xd5, 0xf4, 0x7c, 0xef, 0x64, 0xba, 0x4d, 0x9e, 0xa5, 0x5a, 0x27, 0x46, 0x14, 0xaf,
	0x32, 0x15, 0x26, 0x41, 0x02, 0x7b, 0x80, 0xee, 0xcc, 0xad, 0x32, 0x69, 0x36, 0xf4, 0x14, 0x88,
	0x95, 0x36, 0x13, 0x51, 0x30, 0x0a, 0xe2, 0x3e, 0x2f, 0x01, 0x3d, 0x81, 0xb6, 0x93, 0xeb, 0xa8,
	0x35, 0x0a, 0x62, 0xc2, 0xfd, 0x48, 0x23, 0xe8, 0xa6, 0x5a, 0x59, 0xa1, 0x6c, 0xd4, 0x46, 0x66,
	0x0d, 0xd9, 0x0d, 0x74, 0x6f, 0xf5, 0x6e, 0x27, 0x94, 0xa5, 0x43, 0xe8, 0x39, 0x23, 0x8a, 0xa7,
	0xe5, 0xae, 0xf6, 0xfb, 0xc2, 0x87, 0x06, 0xad, 0x63, 0x83, 0x6b, 0x18, 0x3c, 0x4a, 0x63, 0xb9,
	0xd8, 0x3b, 0x61, 0x2c, 0xa5, 0x10, 0xe6, 0xcb, 0x97, 0xd2, 0x80, 0x70, 0x9c, 0xfd, 0x95, 0xa9,
	0x76, 0x95, 0x94, 0xf0, 0x12, 0xb0, 0xf7, 0x00, 0xc8, 0xc2, 0x07, 0xfa, 0x7d, 0x0a, 0xbf, 0x35,
	0x93, 0x5b, 0x11, 0x85, 0xe5, 0x56, 0x3f, 0xd3, 0xa9, 0x67, 0x63, 0xb2, 0x88, 0x8c, 0xda, 0xf1,
	0x60, 0xc2, 0x92, 0x6f, 0x3b, 0x4d, 0xaa, 0x0e, 0x78, 0x2d, 0x61, 0x6f, 0xf0, 0xdf, 0x1f, 0xa7,
	0xee, 0xb5, 0x54, 0xd8, 0xc0, 0xdf, 0x1c, 0x49, 0x21, 0x54, 0xbe, 0x6f, 0x82, 0x54, 0x9c, 0xd9,
	0x1d, 0xf4, 0xb1, 0x17, 0x5f, 0x2b, 0x9d, 0x7a, 0x91, 0xa9, 0x23, 0xc4, 0x0d, 0x11, 0x8e, 0xce,
	0xe5, 0xa8, 0x62, 0x63, 0xf8, 0x37, 0x73, 0x66, 0xc3, 0x85, 0xc9, 0xb5, 0x32, 0x82, 0x9e, 0x41,
	0xa7, 0x10, 0xc6, 0x65, 0x16, 0x53, 0xf4, 0x78, 0x85, 0x26, 0x1f, 0x41, 0x19, 0x37, 0x9d, 0x57,
	0x9e, 0x74, 0x0e, 0xa1, 0x57, 0xd2, 0xa6, 0xd2, 0xaa, 0x57, 0x38, 0xbc, 0x6c, 0xe4, 0x1c, 0xac,
	0x5f, 0x40, 0x88, 0xa1, 0xc6, 0x0d, 0x82, 0x83, 0xc7, 0x34, 0xbc, 0xf8, 0x21, 0x2e, 0x56, 0xb4,
	0xea, 0xe0, 0x8f, 0xb9, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x65, 0x2c, 0xc4, 0x40, 0x03,
	0x00, 0x00,
}
