// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

package quick_find_services_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginRequest) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type User struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UpdateResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{3}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type AddFriendRequest struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FriendId             int32    `protobuf:"varint,2,opt,name=friendId,proto3" json:"friendId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendRequest) Reset()         { *m = AddFriendRequest{} }
func (m *AddFriendRequest) String() string { return proto.CompactTextString(m) }
func (*AddFriendRequest) ProtoMessage()    {}
func (*AddFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{4}
}

func (m *AddFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendRequest.Unmarshal(m, b)
}
func (m *AddFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendRequest.Marshal(b, m, deterministic)
}
func (m *AddFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendRequest.Merge(m, src)
}
func (m *AddFriendRequest) XXX_Size() int {
	return xxx_messageInfo_AddFriendRequest.Size(m)
}
func (m *AddFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendRequest proto.InternalMessageInfo

func (m *AddFriendRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AddFriendRequest) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

type AddFriendResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendResponse) Reset()         { *m = AddFriendResponse{} }
func (m *AddFriendResponse) String() string { return proto.CompactTextString(m) }
func (*AddFriendResponse) ProtoMessage()    {}
func (*AddFriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{5}
}

func (m *AddFriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendResponse.Unmarshal(m, b)
}
func (m *AddFriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendResponse.Marshal(b, m, deterministic)
}
func (m *AddFriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendResponse.Merge(m, src)
}
func (m *AddFriendResponse) XXX_Size() int {
	return xxx_messageInfo_AddFriendResponse.Size(m)
}
func (m *AddFriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendResponse proto.InternalMessageInfo

func (m *AddFriendResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "quick.find.services.user.LoginRequest")
	proto.RegisterType((*User)(nil), "quick.find.services.user.User")
	proto.RegisterType((*RegisterRequest)(nil), "quick.find.services.user.RegisterRequest")
	proto.RegisterType((*UpdateResponse)(nil), "quick.find.services.user.UpdateResponse")
	proto.RegisterType((*AddFriendRequest)(nil), "quick.find.services.user.AddFriendRequest")
	proto.RegisterType((*AddFriendResponse)(nil), "quick.find.services.user.AddFriendResponse")
}

func init() { proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90) }

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0xe9, 0x47, 0x4a, 0x7b, 0x29, 0xef, 0x5b, 0x2f, 0x22, 0x21, 0x0b, 0x29, 0x59, 0x48,
	0xb4, 0x90, 0x85, 0x6e, 0x04, 0x37, 0xba, 0x11, 0x04, 0x51, 0x18, 0xe9, 0x5a, 0x62, 0xe7, 0x36,
	0x0e, 0xd5, 0x99, 0x74, 0x26, 0x91, 0xfe, 0x6c, 0x7f, 0x82, 0x64, 0x26, 0x0d, 0xb5, 0x98, 0x56,
	0x77, 0x73, 0x66, 0x9e, 0xfb, 0x91, 0x73, 0x08, 0x60, 0x61, 0x48, 0x3f, 0x1b, 0xd2, 0x1f, 0x62,
	0x46, 0x71, 0xa6, 0x55, 0xae, 0xd0, 0x5f, 0x16, 0x62, 0xb6, 0x88, 0xe7, 0x42, 0xf2, 0xb8, 0x7a,
	0x31, 0x71, 0xc9, 0x85, 0x97, 0x30, 0xbc, 0x57, 0xa9, 0x90, 0x8c, 0x96, 0x05, 0x99, 0x1c, 0x0f,
	0xc1, 0xcb, 0x5e, 0x95, 0x24, 0xbf, 0x35, 0x6e, 0x45, 0x03, 0xe6, 0x04, 0x22, 0x74, 0x67, 0x8a,
	0x93, 0xdf, 0x1e, 0xb7, 0x22, 0x8f, 0xd9, 0x73, 0x28, 0xa1, 0x3b, 0x35, 0xa4, 0x71, 0x04, 0x9d,
	0x42, 0x70, 0xcb, 0x7b, 0xac, 0x3c, 0x62, 0x00, 0xfd, 0xb2, 0xf7, 0x43, 0xf2, 0xee, 0x2a, 0x06,
	0xac, 0xd6, 0x25, 0x9d, 0xa4, 0xe4, 0x77, 0x1c, 0x9d, 0xa4, 0xf6, 0xc6, 0xd0, 0xca, 0xef, 0xba,
	0x1b, 0x43, 0xab, 0x72, 0x87, 0x5c, 0x2d, 0x48, 0xfa, 0x9e, 0xdb, 0xc1, 0x8a, 0xf0, 0x0a, 0xfe,
	0x33, 0x4a, 0x85, 0xc9, 0x49, 0xff, 0x7d, 0xd9, 0x08, 0xfe, 0x4d, 0x33, 0x9e, 0xe4, 0xc4, 0xc8,
	0x64, 0x4a, 0x1a, 0xc2, 0x23, 0xe8, 0x69, 0x32, 0xc5, 0x5b, 0x6e, 0x8b, 0xfb, 0xac, 0x52, 0xe1,
	0x35, 0x8c, 0x6e, 0x38, 0xbf, 0xd5, 0x82, 0x24, 0x5f, 0xcf, 0xf9, 0xf1, 0x13, 0xe7, 0x16, 0xb9,
	0xe3, 0xd5, 0x9c, 0x5a, 0x87, 0x13, 0x38, 0xd8, 0xe8, 0xb0, 0x7b, 0xdc, 0xf9, 0x67, 0x1b, 0x86,
	0xa5, 0x8d, 0x4f, 0x55, 0x2a, 0xf8, 0x08, 0x9e, 0x0d, 0x04, 0x4f, 0xe2, 0xa6, 0xd0, 0xe2, 0xcd,
	0xc4, 0x82, 0xe3, 0x66, 0xce, 0xe6, 0x33, 0x85, 0xfe, 0xda, 0x37, 0x3c, 0x6d, 0x66, 0xb7, 0xbc,
	0xdd, 0xdb, 0x96, 0x41, 0xcf, 0x39, 0x8a, 0x7b, 0xc8, 0x20, 0xda, 0xf1, 0xfe, 0x3d, 0x13, 0x0e,
	0x83, 0xda, 0x39, 0x3c, 0x6b, 0x2e, 0xdb, 0x0e, 0x28, 0x98, 0xfc, 0x8a, 0x75, 0x53, 0x5e, 0x7a,
	0xf6, 0x9f, 0xb8, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x37, 0x5e, 0xe1, 0x25, 0x29, 0x03, 0x00,
	0x00,
}
