// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-12-14 13:27:42.01773 +0800 CST m=+0.060433758

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/quick_find/friend/add": {
            "post": {
                "tags": [
                    "Friend Service"
                ],
                "summary": "Add",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the user id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "want to add",
                        "name": "friend_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "schema": {
                            "type": "system"
                        }
                    },
                    "800": {
                        "schema": {
                            "type": "params"
                        }
                    }
                }
            }
        },
        "/quick_find/friend/list": {
            "post": {
                "tags": [
                    "Friend Service"
                ],
                "summary": "List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the user id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "schema": {
                            "type": "system"
                        }
                    },
                    "800": {
                        "schema": {
                            "type": "params"
                        }
                    }
                }
            }
        },
        "/quick_find/user/login": {
            "post": {
                "tags": [
                    "User Service"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "phone number",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "phone code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "schema": {
                            "type": "system"
                        }
                    },
                    "800": {
                        "schema": {
                            "type": "params"
                        }
                    }
                }
            }
        },
        "/quick_find/user/register": {
            "post": {
                "tags": [
                    "User Service"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "type": "string",
                        "description": "phone number",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "phone code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "schema": {
                            "type": "system"
                        }
                    },
                    "800": {
                        "schema": {
                            "type": "params"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
