info:
  contact: {}
  license: {}
paths:
  /quick_find/friend/add:
    post:
      parameters:
      - description: the user id
        in: query
        name: uid
        required: true
        type: string
      - description: want to add
        in: query
        name: friend_id
        required: true
        type: integer
      responses:
        "800":
          schema:
            type: params
        "1000":
          schema:
            type: system
      summary: Add
      tags:
      - Friend Service
  /quick_find/friend/list:
    post:
      parameters:
      - description: the user id
        in: query
        name: uid
        required: true
        type: string
      responses:
        "800":
          schema:
            type: params
        "1000":
          schema:
            type: system
      summary: List
      tags:
      - Friend Service
  /quick_find/im/send:
    post:
      parameters:
      - description: from id
        in: query
        name: from
        required: true
        type: integer
      - description: to id
        in: query
        name: to
        required: true
        type: integer
      - description: message
        in: query
        name: message
        required: true
        type: string
      responses:
        "800":
          schema:
            type: params
        "1000":
          schema:
            type: system
      summary: send
      tags:
      - IM Service
  /quick_find/im/translate:
    post:
      parameters:
      - description: text
        in: query
        name: text
        required: true
        type: string
      responses:
        "800":
          schema:
            type: params
        "1000":
          schema:
            type: system
      summary: translate
      tags:
      - IM Service
  /quick_find/topic/list:
    post:
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: count
        in: query
        name: count
        required: true
        type: integer
      - description: want to add
        in: query
        name: uid
        required: true
        type: integer
      responses:
        "800":
          schema:
            type: params
        "1000":
          schema:
            type: system
      summary: publish
      tags:
      - Topic Service
  /quick_find/topic/publish:
    post:
      parameters:
      - description: content of the topic
        in: query
        name: content
        required: true
        type: string
      - description: title of the topic
        in: query
        name: title
        required: true
        type: string
      - description: want to add
        in: query
        name: uid
        required: true
        type: integer
      responses:
        "800":
          schema:
            type: params
        "1000":
          schema:
            type: system
      summary: publish
      tags:
      - Topic Service
  /quick_find/user/login:
    post:
      parameters:
      - description: phone number
        in: query
        name: phone
        required: true
        type: string
      - description: phone code
        in: query
        name: code
        required: true
        type: integer
      responses:
        "800":
          schema:
            type: params
        "1000":
          schema:
            type: system
      summary: Login
      tags:
      - User Service
  /quick_find/user/register:
    post:
      parameters:
      - description: phone number
        in: query
        name: phone
        required: true
        type: string
      - description: phone code
        in: query
        name: code
        required: true
        type: integer
      responses:
        "800":
          schema:
            type: params
        "1000":
          schema:
            type: system
      summary: Register
      tags:
      - User Service
